---
title: "Reveiw Questions"
output: html_document
---

Informations

Chris: chris.brown **at** decisionpatterns.com
Google Group: CSX460
Github: https://github.com/csx460


All assignments should be submitted to the github repository using a branch created wit you initials. For Example,

    git clone https://github.com/csx460/week2
    git checkout -b ctb
    (work)
    git add ...
    git commit ...
    git push into your repo and issue a pull request.    


Place answers directly in the files.

Feel free to push your answers when you are complete 


Assignments:

* Please Read Chapters 1-3 of Applied Predictive Modeling 


* Submit via email a project proposal: A description of your project that includes:
** The objective, what you expect to achieve with the model
** data source(s)
** responses
** expected (hypothesized) predictors
** how the model will be used 
** how you will determine the measure of success of the model


# 1.  Do the boston-housing.Rmd assignment in github.
Don't forget to show your works, plots included.


# 2. Algorithms and Functions

When speaking of Machine Learning, there are two functions or algorithms involved.
Describe and differentiate the algorithms from the function.

Answer:  An  algorithm is a method used to select a prediction function from a 
space of possible prediction functions.  The prediction function itself is used to map
input data to predicted outcomes.  Another function is defined to measure 
the error of the prediction function (for example RMSE).



# 2. RMSE and MAE

Why is RMSE preferrable to MAE?  
When is MAE better? 

ANSWER:  RMSE is generally preferable to MAE when it is appropriate to penalize
large errors disproportionately to small ones (square of the error as opposed 
to the absolute value of the error).I've also read that RMSE is particularly useful
when one expects the errors to follow a gaussian distribution.  MAE may be better in cases
where larger errors are not greatly worse than small ones.  MAE is also less sensative to outliers.

